# Generated by Django 4.2.7 on 2024-01-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='departure_time',
            field=models.DateTimeField(null=True),
        ),
    ]
